export const projectsData = [
  {
    to: "/",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample119.jpg",
    alt: "sample119",
    primaryColor: "#f12711",
    secondaryColor: "#f5af19",
    caption: "Easy to Use",
  },
  {
    to: "/",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample119.jpg",
    alt: "sample119",
    primaryColor: "#f12711",
    secondaryColor: "#f5af19",
    caption: "Easy to Use",
  },
  {
    to: "/",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample119.jpg",
    alt: "sample119",
    primaryColor: "#00c6ff",
    secondaryColor: "#0072ff",
    caption: "Easy to Use",
  },
  {
    to: "#",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample87.jpg",
    alt: "sample87",
    primaryColor: "#7303c0",
    secondaryColor: "#ec38bc",
    caption: "Endless Possibilities",
  },
  {
    to: "#",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample87.jpg",
    alt: "sample87",
    primaryColor: "#7303c0",
    secondaryColor: "#ec38bc",
    caption: "Endless Possibilities",
  },
  {
    to: "#",
    src: "https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample87.jpg",
    alt: "sample87",
    primaryColor: "#7303c0",
    secondaryColor: "#ec38bc",
    caption: "Endless Possibilities",
  },
];
